### ISSUE TITLE
weight axis uses a non-standard scale

### ISSUE THREAD

**Issue by jfkthame** [impallari/Cabin#17]
The weight axis ranges from 95..128, with the Regular face being at the beginning of the range. This will not interoperate well with weights as defined in OpenType or CSS, where a Regular face is expected to have weight:400. I would suggest re-scaling the axis to a range of, for example, 400..700 for the weight variation that is actually available.

**Comment by caraya** [comment]
Values from 1 to 999 and all intermediate values are valid so 100 - 900 are no longer the only way that you can write your weight declarations for variable fonts (they remain the standard for non variable fonts, however).  You'll find yourself in this problem with every variable font you use, not just Cabin

Cabin also has predefined axes that give you the combinations that you need to get a given font weight.  You can use `font-variation-settings` directly when defining my elements and classes or I use tools like [wakamaifondue](https://wakamaifondue.com/) to get a list of all the predefined instances along with open type features available for the font. It also generates CSS that you can drop into your own stylesheets. 

If you don't feel like using the tools, this CSS works for me in browsers that support variable fonts.

```css
/* Variable instances */
.cabin-vf-beta-regular {
    font-variation-settings: "wght" 94, "wdth" 100;
}

.cabin-vf-beta-medium {
    font-variation-settings: "wght" 109, "wdth" 100;
}

.cabin-vf-beta-semibold {
    font-variation-settings: "wght" 116, "wdth" 100;
}

strong, 
b,
.cabin-vf-beta-bold {
    font-variation-settings: "wght" 128, "wdth" 100;
}
```
